rpc:
  enable: true
  bind: :8080
proxy:
  enable: false
  http_url: ""
  https_url: ""
  username: ""
  password: ""
debug: false
interval: 20
out_put_path: /srv/bililive
feature:
  use_native_flv_parser: false
live_rooms:
